name: SP.Core.Common CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dotnet-ci:
    uses: Somasundar-Projects/DevOps/.github/workflows/dotnet_build.yml@main
    with:
      dotnet-versions: '["8.x","9.x"]'
      project_path: SP.Core.Common.sln
